version: "3.7"

services:
  backend:
    image: backend
    build: ../backend
    working_dir: /var/www
    container_name: backend
    command: php -S 0.0.0.0:8080
    depends_on:
      - postgresql

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ../frontend:/var/www
      - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - postgresql

  postgresql:
    image: postgres
    container_name: postgresql
    volumes:
      - ../postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres